server:
  port: 10000

spring:
  application:
    name: gateway-server

  cloud:     #注意是spring旗下的,必须写在这,不能另起
    gateway:
      routes:
        # 路由id，可以任意
        - id: user-service-route
          # 代理的服务地址,这里基于ribbon,loadbalance基于服务名,负载均衡
          uri: lb://user-server
          # 路由断言： 是一个集合,可以设置条件如:匹配映射路径
          predicates:
            - Path=/api/user/**

          # 局部过滤器,只对当前路由生效
          filters:
            # 表示过滤1个路径，2表示两个路径，以此类推
            - StripPrefix=1

        - id: order-service-route
          # 代理的服务地址,这里基于ribbon,loadbalance基于服务名,负载均衡
          uri: lb://order-server
          # 路由断言： 是一个集合,可以设置条件如:匹配映射路径
          predicates:
            - Path=/api/order/**

          # 局部过滤器,只对当前路由生效
          filters:
            # 表示过滤1个路径，2表示两个路径，以此类推
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/


